_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  anonymous_login: 0
  auto_entitylabel: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  bpmn_io: 0
  breakpoint: 0
  cheeseburger_menu: 0
  ckeditor5: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  colorbox: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_cart_redirection: 0
  commerce_checkout: 0
  commerce_log: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_payment_example: 0
  commerce_price: 0
  commerce_product: 0
  commerce_product_restriction: 0
  commerce_promotion: 0
  commerce_store: 0
  conditional_fields: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  disable_messages: 0
  drupal_telegram_sdk: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_cache: 0
  eca_config: 0
  eca_content: 0
  eca_endpoint: 0
  eca_form: 0
  eca_log: 0
  eca_migrate: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_render: 0
  eca_state_machine: 0
  eca_tamper: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  edit_own_user_account_permission: 0
  editablefields: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  faqfield: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  flexible_permissions: 0
  foundation_layouts: 0
  gnode: 0
  group: 0
  group_action: 0
  group_support_revisions: 0
  help: 0
  hide_preview: 0
  history: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  k1_theme_switcher: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  login_destination: 0
  masquerade: 0
  maxlength: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_item_role_access: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  mysql: 0
  node: 0
  nodeaccess: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  r4032login: 0
  redirect_404: 0
  search: 0
  shortcut: 0
  simple_popup_blocks: 0
  simple_popup_views: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smart_date: 0
  smart_date_recur: 0
  smtp: 0
  state_machine: 0
  system: 0
  tab_manager: 0
  tamper: 0
  taxonomy: 0
  telegram_api: 0
  telegram_bot: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  ultimate_cron: 0
  update: 0
  user: 0
  variationcache: 0
  verf: 0
  views_conditional: 0
  views_dynamic_fields_and_filters: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflow: 0
  workflow_access: 0
  workflows: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  stable: 0
  zurb_foundation: 0
  gamecrm: 0
  gamecrm_dark: 0
  gamecrm_sakura: 0
profile: standard
