_core:
  default_config_hash: Ra1wCOv-XTOsjio08D1i49hzjcUlin66zuciiPtpV44
disable_messages_enable: '1'
disable_messages_exclude_users: ''
disable_messages_filter_by_page: 0
disable_messages_page_filter_paths: ''
disable_messages_enable_debug: '0'
disable_messages_debug_visible_div: '0'
disable_messages_ignore_patterns: 'There are no workflow states available. Please notify your site administrator.'
disable_messages_enable_permissions: '0'
disable_messages_ignore_exclude: '0'
disable_messages_ignore_case: '1'
disable_messages_strip_html_tags: '1'
disable_messages_ignore_regex:
  - '/^There are no workflow states available. Please notify your site administrator.$/i'
