_core:
  default_config_hash: LlLLIebeSLQ6abyM6-RlwWhLDbMf8I5hj6hxZvq8Dik
zurb_foundation_disable_base_css: 1
zurb_foundation_disable_base_js: 1
features:
  node_user_picture: 0
  comment_user_picture: 1
  favicon: 1
favicon:
  use_default: 1
zurb_foundation_status_in_reveal: 0
zurb_foundation_meta_header_grid: 0
zurb_foundation_top_bar_enable: '0'
zurb_foundation_top_bar_grid: 0
zurb_foundation_top_bar_sticky: 0
zurb_foundation_top_bar_is_hover: 0
zurb_foundation_top_bar_menu_text: ''
zurb_foundation_top_bar_custom_back_text: 0
zurb_foundation_top_bar_back_text: ''
zurb_foundation_top_bar_search: 0
zurb_foundation_block_copyright_show: 1
zurb_foundation_block_copyright_custom_text: 1
zurb_foundation_block_copyright_text: 'Copyright © 2023 K1-Team. All rights reserved.'
