_core:
  default_config_hash: ev_QLQNwc0-1EGokxDRzrPpUi1kLXjeBRd5vhwpB6h0
allowed_grant_operations:
  grant_view: true
  grant_update: true
  grant_delete: true
bundles_roles_grants:
  article:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    team_lead:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    user:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  balance:
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    team_lead:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    user:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  mission:
    administrator:
      grant_view: 1
      grant_update: 0
      grant_delete: 1
    team_lead:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    user:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 1
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  page:
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    team_lead:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    user:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
  transaction:
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    team_lead:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    user:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    anonymous:
      grant_view: 0
      grant_update: 0
      grant_delete: 0
grants_tab_availability:
  article: false
  balance: false
  mission: false
  page: false
  transaction: false
map_rid_gid:
  anonymous: 0
  authenticated: 1
  content_editor: 2
  administrator: 3
  team_lead: 4
  user: 5
roles_settings:
  anonymous:
    display_name: 'Anonymous user'
    name: 'Anonymous user'
    weight: 0
    selected: false
  authenticated:
    display_name: 'Authenticated user'
    name: 'Authenticated user'
    weight: 0
    selected: false
  content_editor:
    display_name: 'Content editor'
    name: 'Content editor'
    weight: 0
    selected: false
  administrator:
    display_name: Administrator
    name: Administrator
    weight: 0
    selected: false
  team_lead:
    display_name: 'Team lead'
    name: 'Team lead'
    weight: 0
    selected: false
  user:
    display_name: User
    name: User
    weight: 0
    selected: false
